data:
  num_classes: 11
  ignore_label: 255
  training_size: 19132

train:
  seed: 1588147245
  deterministic: False

src_dataset1:
  name: semantickitti
  root: /l/users/junchen.liu/pcl_dataset/kitti_sematic/dataset/sequences
  num_points: 80000
  voxel_size: 0.05

src_dataset2:
  name: synlidar
  root: /l/users/junchen.liu/pcl_dataset/SynLiDAR/SubDataset/sequences
  num_points: 80000
  voxel_size: 0.05

src_dataset3:
  name: semanticposs
  root: /l/users/junchen.liu/pcl_dataset/SemanticPOSS/dataset/sequences
  num_points: 80000
  voxel_size: 0.05

tgt_dataset:
  name: semanticstf
  root: /l/users/junchen.liu/pcl_dataset/SemanticSTF
  num_points: 80000
  voxel_size: 0.05

num_epochs: 50
batch_size: 8

criterion:
  name: cross_entropy
  ignore_index: 255

optimizer:
  name: sgd
  lr: 1.0e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup
